[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git log -1 --pretty=%B | grep dependabot"
    [build.processing]
        skip_processing = true

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
