[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https:; frame-ancestors 'none';"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cache-Control = "public, max-age=10000, must-revalidate"

[[headers]]
  for = "/**/*.{js,css,jpg,jpeg,png,gif,webp}"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
