[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git log -1 --pretty=%B | grep dependabot"


[[headers]]
    for = "/*"

    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        cache-control = "public, max-age=10000, must-revalidate"